[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip && pip install -r bot/requirements.txt"
buildImage = "python:3.11"

[deploy]
startCommand = "python bot/app.py"

[variables]
PYTHONUNBUFFERED = "1"
